xgboost:
  learning_rate: 0.1
  max_depth: 4
  colsample_bytree: 0.65
  colsample_bylevel: 0.65
  reg_alpha: 0.0007
  n_estimators: 2000


lightgbm:
  learning_rate: 0.1
  max_depth: 9
  num_leaves: 10
  colsample_bytree: 0.75
  reg_alpha: 0.0001
  reg_lambda: 0.0001
  n_estimators: 2000
  verbosity: -1