learning_rate: 0.01
max_depth: 4
colsample_bytree: 0.8
colsample_bylevel: 0.8
reg_alpha: 0.0007
n_estimators: 100000
min_child_weight: 2.0
gamma: 1.0
reg_lambda: 1.0
subsample: 0.8
verbosity: 0               
